### ISSUE TITLE
Replay CLI can fail if the recordings file gets too big

### ISSUE THREAD

**Issue by jcmorrow** [replayio/replay-cli#21]
@bvaughn ran into this this morning when trying to debug some Playwright tests. It's a little unclear why he would have had so many replays exactly, but anyways, he got this when trying to run `npx replay ls`:

```
$ replay ls
node:buffer:593
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:593:37)
    at Buffer.toString (node:buffer:811:14)
    at Object.readFileSync (node:fs:497:41)
    at readRecordingFile (/Users/bvaughn/.nvm/versions/node/v16.13.2/lib/node_modules/@replayio/replay/src/main.js:34:13)
    at readRecordings (/Users/bvaughn/.nvm/versions/node/v16.13.2/lib/node_modules/@replayio/replay/src/main.js:65:17)
    at listAllRecordings (/Users/bvaughn/.nvm/versions/node/v16.13.2/lib/node_modules/@replayio/replay/src/main.js:225:22)
```

**Comment by bvaughn** [comment]
Note a temporary work around for this is to remove cached metadata: `rm -rf ~/.replay`
