### ISSUE TITLE
Error when using the `reporter` argument

### ISSUE THREAD

**Issue by ChaiWithJai** [replayio/replay-cli#87]
Getting the following error message when running the `npx playwright test --project replay-firefox --reporter=@replayio/playwright/reporter,line` command:

```
Error: node_modules/@replayio/playwright/reporter.js: reporter file must export a single class.
    at errorWithFile (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/util.js:189:10)
    at Loader.loadReporter (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/loader.js:180:67)
    at Runner._createReporter (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/runner.js:132:37)
    at Runner.runAllTests (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/runner.js:167:22)
    at runTests (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/cli.js:175:18)
    at Command.<anonymous> (/Users/jaibhagat/hashicorp/nomad/e2e/ui/node_modules/@playwright/test/lib/cli.js:74:7)
```

**Comment by Andarist** [comment]
I can't repro this problem. If you manage to provide a repro case I could take another look at this. A lot has changed here since the issue was opened though so perhaps this just got fixed in the meantime.
